name: example
description: A new Flutter project.

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fancy_shimmer_image:
    path: ../
  random_color: ^1.0.6-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
