name: fancy_shimmer_image
description: Package for easy use of images that are automatically cacheable and have a beautiful on the fly (but it can be configured) shimmer effect while loading
version: 1.0.0
author: Rodrigo Vasconcelos <rodrigobastosv@gmail.com>
homepage: https://github.com/rodrigobastosv/fancy-shimmer-image

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^1.1.3
  shimmer: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
